print("###################################")
print("#                                 #")
print("#   A. Malik Fajar Putra Syamsi   #")
print("#        2410817210020            #")
print("#                                 #")
print("###################################")