Nama = input("Nama                       : ")
NIM = int(input("NIM                        : "))
Kelas_Paralel = input("Kelas Paralel              : ")
TTL = input("Tempat/Tanggal Lahir       : ")
Alamat = input("Alamat                     : ")
hobby = input("Hobby                      : ")
Hp = int(input("No. HP                     : "))

print("Nama                       :", Nama)
print("NIM                        :", NIM)
print("Kelas Paralel              :", Kelas_Paralel)
print("Tempat/Tanggal Lahir       :", TTL)
print("Alamat                     :", Alamat)
print("Hobby                      :", hobby)
print("No. HP                     :", Hp)